### PR TITLE
Completed Logging migration and better GraphView DB handling. Fixes #958

### LINKED ISSUE #958: Failed to build on Fedora20
I followed the guide to build apmplanner2 but build fails with error:

rc/QGCCore.cc: In member function 'void QGCCore::initialize()':
src/QGCCore.cc:89:11: error: 'qInfo' was not declared in this scope
     QLOG_INFO() << "QGCCore::initialize()";
           ^
src/QGCCore.cc: In member function 'void QGCCore::startLinkManager()':
src/QGCCore.cc:233:11: error: 'qInfo' was not declared in this scope
     QLOG_INFO() << "Start Link Manager";
           ^
src/QGCCore.cc: In member function 'void QGCCore::startUASManager()':
src/QGCCore.cc:243:11: error: 'qInfo' was not declared in this scope
     QLOG_INFO() << "Start UAS Manager";
           ^
make: *** [build-release/obj/QGCCore.o] Error 1
ошибка: Неверный код возврата из /var/tmp/rpm-tmp.vC8yX6 (%build)

Ошибки сборки пакетов:
    Неверный код возврата из /var/tmp/rpm-tmp.vC8yX6 (%build)

Previous version 2.0.16        rc1.32.gc208324 builds OK

### PR DESCRIPTION
**Pull request by Arne-W**
It's done !!
I have removed the complete QsLog code, introduced a new header containing the macros and changed all includes. 
The building issues regarding the qInfo() macro should be fixed due to a replacement with qDebug() if Qt version is smaller than 5.5.0.
And I fixed the DB issue in the graph view code which caused a resource leak.

### CODE REVIEW

**Comment by rvminko** [comment]
Issue comes back or still reproduce in some circumstance
Ubuntu 16.04 before and after update at 17.12.2016
QMake version 3.0
Using Qt version 5.6.1 in /usr/lib/x86_64-linux-gnu
KDE frameworks version 5.28

> src/uas/UASManager.cc: In member function ‘bool UASManager::setHomePosition(double, double, double)’:
src/uas/UASManager.cc:76:19: error: ‘isnan’ was not declared in this scope
     if (!isnan(lat) && !isnan(lon) && !isnan(alt)
                   ^
src/uas/UASManager.cc:76:19: note: suggested alternative:
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:88,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h:37,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h:37,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QList:1,
                 from src/uas/UASManager.cc:11:
/usr/include/c++/5/cmath:641:5: note:   ‘std::isnan’
     isnan(_Tp __x)
     ^
src/uas/UASManager.cc:77:22: error: ‘isinf’ was not declared in this scope
         && !isinf(lat) && !isinf(lon) && !isinf(alt)
                      ^
src/uas/UASManager.cc:77:22: note: suggested alternative:
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:88,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h:37,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h:37,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QList:1,
                 from src/uas/UASManager.cc:11:
/usr/include/c++/5/cmath:621:5: note:   ‘std::isinf’
     isinf(_Tp __x)
     ^
Makefile:34507: recipe for target 'build-release/obj/UASManager.o' failed
make: *** [build-release/obj/UASManager.o] Error 1
>

**Comment by billbonney** [comment]
This must be some dependency issue or not using a clean build. I've integrated APM Planner GitHub with Travis CI build system. As you can see from here it builds on 14.04 (it needs a manually download version of Qt5.5.1)

https://travis-ci.org/ArduPilot/apm_planner/builds/183501413

You can look at the .travis.yml to see the dependencies installed. https://github.com/ArduPilot/apm_planner/blob/master/.travis.yml

The # out Qt dependencies are required if you use Qt5 supplied with 16.04+

**Comment by Arne-W** [comment]
Hmmm on my machine (Ubuntu 16.04) the Qt 5.5.1 is ok and the Qt 5.6.2 fails... was a clean build...
