### ISSUE TITLE
Compile error on Linux (CentOS 7 64bit)

### ISSUE THREAD

**Issue by hsteinhaus** [ArduPilot/apm_planner#883]
Compilation of master fails:

src/GAudioOutput.cc:401:12: error: 'flite_voice_list' was not declared in this scope
     for (v=flite_voice_list; v; v=val_cdr(v)) {

flite-dev is installed here (flite-devel-1.3-22.el7.x86_64). 

Regarding to grep, the symbol "flite_voice_list", does not appear in the whole source tree again.
I guess the problem was introduced by commit 4d67d34d7b6752b796198342f2de62c9c96be5b8 . After reverting it, everything seems to work again.

**Comment by froller** [comment]
Same issue on Fedora 24

**Comment by Evidlo** [comment]
I have this issue on Fedora 25.

**Comment by iamjkp** [comment]
Same issue on Fedora 25. 

I am removing 2 lines in apm_planner.pro file and then compiling is successful. 

I reference above guys comments. Just remove `DEFINES += FLITE_AUDIO_ENABLED` code in apm_planner.pro. Everything will work out. 

Thanks guys.

**Comment by larsks** [comment]
@madflower I just ran into the same issue (`error: 'flite_voice_list' was not declared...`).  Is this just some sort of version skew in flite? Fedora 25 has flite 1.3.

**Comment by cafeclimber** [comment]
Has this issue been fixed? Experiencing the same issue on Fedora 26

**Comment by larsks** [comment]
This is fixed in #1065, but so far nobody has reviewed or merged that patch.
